    var photos = [
        {id: "img-01", thumb: "img/t01.png", src: "img/36001.JPG", desc: "Bruarfoss: Tiffany 藍瀑布"},
        {id: "img-02", thumb: "img/t02.png", src: "img/36002.JPG", desc: "極光爆發，這晚的極光不太會動，很適合攝影"},
        {id: "img-03", thumb: "img/t03.png", src: "img/36003.JPG", desc: "Seljalandsfoss: 水濂洞瀑布"},
        {id: "img-04", thumb: "img/t04.png", src: "img/36004.JPG", desc: "Skogafoss: 彩虹瀑布，你看到彩虹了嗎？"},
        {id: "img-05", thumb: "img/t05.png", src:["img/36005.JPG",
                                                  "img/36006.JPG",
                                                  "img/36007.JPG",
                                                  "img/36008.JPG",
                                                  "img/36009.JPG",
                                                  "img/36010.JPG",
                                                  "img/36011.JPG",
                                                  "img/36012.JPG",
                                                  "img/36013.JPG",
                                                  "img/36014.JPG",
                                                  "img/36015.JPG",
                                                  "img/36016.JPG",
                                                  "img/36017.JPG",
                                                  "img/36018.JPG",
                                                  "img/36019.JPG",
                                                  "img/36020.JPG",
                                                  "img/36021.JPG",
                                                  "img/36022.JPG",
                                                  "img/36023.JPG",
                                                  "img/36024.JPG",
                                                  "img/36025.JPG"],desc: "極光爆發，一起抬頭看看極光跳舞吧！"},
        {id: "img-06", thumb: "img/t06.png", src: "img/36026.JPG", desc: "Skaftafell 冰川健行"},
        {id: "img-07", thumb: "img/t07.png", src: "img/36027.JPG", desc: "Crystal Ice Cave 藍冰洞"},
        {id: "img-08", thumb: "img/t08.png", src: "img/36028.JPG", desc: "Jökulsárlón 冰河湖"},
        {id: "img-09", thumb: "img/t09.png", src: "img/36029.JPG", desc: "順路經過的冰島馬小農場"},
        {id: "img-10", thumb: "img/t10.png", src: "img/36030.JPG", desc: "Sellfoss 環狀瀑布"},
        {id: "img-11", thumb: "img/t11.png", src: "img/36031.JPG", desc: "米湖地熱區，地熱不間斷的噴發"},
        {id: "img-12", thumb: "img/t12.png", src: "img/36032.JPG", desc: "Goðafoss 眾神瀑布"},
        {id: "img-13", thumb: "img/t13.png", src: "img/36033.JPG", desc: "順路經過的冰島馬，冰島馬真的不太怕人"},
        {id: "img-14", thumb: "img/t14.png", src: "img/36034.JPG", desc: "Kolugljúfur 五爪瀑布，橋的一邊是冬天、一邊是春天"},
        {id: "img-15", thumb: "img/t15.png", src: "img/36035.JPG", desc: "Kirkjufell 教堂山"}
    ]
